image: node:22

default:
  interruptible: true
  timeout: 1 minute

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm run build
  only:
    variables:
      - $CI_DEFAULT_BRANCH != $CI_COMMIT_REF_NAME

pages:
  stage: deploy
  script:
    - npm run build
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    variables:
      - $CI_DEFAULT_BRANCH == $CI_COMMIT_REF_NAME
